use std::collections::HashSet;
use std::sync::OnceLock;
use stop_words::LANGUAGE;

pub fn is_stopword(token: &str) -> bool {
    english_stopwords().contains(token) || POLLING_STOPWORDS.contains(&token)
}

fn english_stopwords() -> &'static HashSet<&'static str> {
    static ENGLISH_STOPWORDS: OnceLock<HashSet<&'static str>> = OnceLock::new();
    ENGLISH_STOPWORDS.get_or_init(|| stop_words::get(LANGUAGE::English).iter().copied().collect())
}

const POLLING_STOPWORDS: &[&str] = &[
    "adult",
    "adults",
    "action",
    "american",
    "americans",
    "answer",
    "approve",
    "asked",
    "believe",
    "candidate",
    "citizen",
    "citizens",
    "country",
    "current",
    "direction",
    "disapprove",
    "doing",
    "dont",
    "election",
    "feel",
    "following",
    "generally",
    "heading",
    "important",
    "increase",
    "increasingly",
    "ipsos",
    "issue",
    "issues",
    "january",
    "february",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december",
    "latest",
    "less",
    "more",
    "most",
    "overall",
    "oppose",
    "opposed",
    "ballot",
    "held",
    "primary",
    "vote",
    "voted",
    "poll",
    "polling",
    "polls",
    "question",
    "right",
    "reuter",
    "reuters",
    "respond",
    "respondent",
    "respondents",
    "say",
    "saying",
    "speaking",
    "somewhat",
    "strong",
    "strongly",
    "support",
    "survey",
    "thing",
    "things",
    "think",
    "time",
    "today",
    "total",
    "track",
    "trump",
    "views",
    "voter",
    "voters",
    "washington",
    "wrong",
    "worth",
];
